# Generated by Django 5.1.7 on 2025-03-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_clinician_state_alter_clinician_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinician',
            name='state',
            field=models.CharField(default='Alberta', max_length=30),
        ),
    ]
